config/routes.rb
Rails.application.routes.draw do
   get 'contacts/new'

  devise_for :accounts,  skip: :registrations
  get 'categories/index'

  root 'plants#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'chat' =>'chats#index'
  get 'login'    => 'sessionss#new'
  get 'registry' => 'accountss#new'
  post 'registry' => 'accountss#create'
   
  delete 'login' => 'sessionss#destroy'
  controller :sessionss do
      post 'login'   => :create
      get 'sessionss/destroy' => 'sessionss#destroy'
  end

  resources :accountss do
     member do
          post "edit" => 'accountss#update'
    end
  end
  controller :accountss do
        post 'accountss/new' => 'accountss#create'
  end
  resources :plants
  resources :categories
  resources :contacts 
  resources :shops
  resources :searchs
  resources :news
  resources :advs do
    get 'destroy'
    get 'destroy_message'
    member do
          post "edit" => 'advs#update'
    end
    collection do
          get 'advs/add_message'
    end
  end
  controller :advs do
        post 'advs/new' => 'advs#create'
  end
  controller :contacts do
        post 'contacts/new' => 'contacts#create'
    end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      # user ||= User.new # guest user (not logged in)
      # if user.role? :member
      #   can :manage, :all
      #   can :access, :rails_admin
      # else
      #    can :manage, [Plant]
      #    can :access, :rails_admin
      # end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities                 # allow everyone to read everything
    $session_account_admin = nil
    if user && user.admin?
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard                  # allow access to dashboard
      if user.role? :super_admin
        can [:read, :destroy], PostSell    
        can [:read, :destroy], UserAccount  
        can :manage, [Plant, PlantImage, Account, Category, Post, Shop, Technical, Contact, Role]            # allow superadmins to do anything
      elsif user.role? :member
         can [:read, :create, :update], [Plant, PlantImage, Post, Technical, Shop]
         can [:read, :destroy], Contact
         can [:show, :update], Account, :id => user.id
      elsif user.role? :guest
        # can :update, Product, :hidden => false  # allow sales to only update visible products
      end
      $session_account_admin = user.id
    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :validatable

   has_and_belongs_to_many  :roles 
   has_many :posts
   accepts_nested_attributes_for :roles
	def role?(role)
	    return !!self.roles.find_by_name(role.to_s)
	end

  before_save do
    self.image = self.file.original_file
  end

	mount_uploader :image, ImageUploader
end

app/models/accounts_role.rb
class AccountsRole < ActiveRecord::Base
	belongs_to :account
	belongs_to :role
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :plants
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, :email, :phone_number, :description,
     	:presence =>  { :message => "Không được để trống" }, :on => :create
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user_account
	belongs_to :post_sell
end

app/models/plant.rb
class Plant < ActiveRecord::Base
  belongs_to :category
  has_many :plant_images
  belongs_to :technical

  accepts_nested_attributes_for :plant_images

  validates :technical, :category, presence: true

end

app/models/plant_image.rb
class PlantImage < ActiveRecord::Base
  belongs_to :plant

  mount_uploader :image, ImageUploader

  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :account

  mount_uploader :image, ImageUploader
end

app/models/post_sell.rb
class PostSell < ActiveRecord::Base
	self.inheritance_column = :foo
	belongs_to :user_account
	has_many :messages

	mount_uploader :image, ImageUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
 has_and_belongs_to_many :accounts
end

app/models/shop.rb
class Shop < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/technical.rb
class Technical < ActiveRecord::Base
  has_one :plant
end

app/models/user_account.rb
class UserAccount < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	has_many :post_sells 
  has_many :messages
  #validate cant be blank
  	validates :name, :usename, :password, :phone_number,
     	:presence =>  { :message => "Không được để trống" }, :on => :create

    #validate number text
  	validates :phone_number, 
  		numericality: { only_integer: true, :message=>"Chỉ được nhập số tự nhiên"},
  		length: { minimum: 10, too_short: " Tối thiểu 10 chữ số",
                maximum: 11, too_long: " Tối đa 11 chữ số" }
  		# length: { maximum: 11, too_long: " Tối đa 11 chữ số" }

  	#validate lenght
  	validates :name, :usename, :password, :address, 
  		length: { minimum: 8, too_short: " Độ dài tối thiểu 8 ký tự" },
  		length: { maximum: 255, too_long: "Chỉ nhập tối đa 255 ký tự" }

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  layout 'public'

  def index
  	@list_post = Post.all.order('created_at')
  				.page(params[:page]).per(per_page)
  end

  def show
  	@list_post_item = Post.find(params[:id])
  end

  private
  	def per_page
    	@per = 6
    	if params[:per]
        	@per = params[:per]
    	end
      @per
    end
  
end

app/helpers/advs_helper.rb
module AdvsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/news/index.html.erb
<section>

<div id="container">

<div class="container">
<div id="notification"></div>
<div class="row">
<div class="span12">
<div class="row">
<div class="span12  " id="content">  <div class="breadcrumb">
		<a href="<%=plants_path%>">Home</a>
		 &raquo; <a href="<%=news_index_path%>">CẨM NANG THỦY SINH</a>
	  </div>
  <h1 class="style-1">DANH SÁCH BÀI VIẾT</h1>
    
      
  <div class="product-grid">
	<ul>
<% @list_post.each do |pl|%>
<li class="span6 ">
	<div class="image"><a href=""><%=image_tag pl.image, id: 'img_40', style: 'width:229px; height:150px' %></a></div>
	<div class="name"><%=link_to pl.title %></div>
	<div class="description">
	<span style= "color:#002AE1">Mô tả:&nbsp;</span><%= pl.detail%>
		<br/>
	<%="<span style= 'color:#002AE1'>Ngày đăng: </span>".html_safe + pl.created_at.strftime("%Y/%m/%d")%>
	</div>

		<div class="cart-button button details"><a href="<%=news_path(pl.id)%>" class="button details" title="Đọc tiếp"><!--<i class="icon-shopping-cart"></i>--><span>Đọc tiếp</span></a>

	</div>
	<div class="rating">
	</div>
</li>
<%end%>
			 </ul>
  </div>
  
  <div class="pagination"><div class="links"> <%=paginate @list_post%></div></div>
      </div>
	</div>
</div>

<script type="text/javascript"><!--
function display(view) {
	if (view == 'list') {
		$('.product-grid ').attr('class', 'product-list');
		$('.product-list ul').removeClass('row');
		$('.product-list ul li').removeClass('span3');
		$('.product-list ul li').each(function(index, element) {
			html = '';
					html += '<div class="row">';
			var image = $(element).find('.image').html();
			
			if (image != null) {
				html += '<div class="image span2">' + image + '</div>';
			}
			html += '<div class="left span6">';
				html += '<div class="name">' + $(element).find('.name').html() + '</div>';
				html += '<div class="description">' + $(element).find('.description').html() + '</div>';

				html += '<div class="button details" style="float:right">' + $(element).find('.details').html() + '</div>';
				
				html += '<div class="clear">' + $(element).find('.clear').html() + '</div>';

				var rating = $(element).find('.rating').html();
				if (rating != null) {
					html += '<div class="rating">' + rating + '</div>';
				}
				html += '</div>';
				html += '</div>';
			

						
			$(element).html(html);
		});		
		
		$('.display').html('<b>Display:</b> <div id="list_b"><i class="icon-list"></i></div> <a id="grid_a" onclick="display(\'grid\');"><i class="icon-th"></i></a>');
		
		$.totalStorage('display', 'list'); 
	} else {
		$('.product-list').attr('class', 'product-grid');
		$('.product-grid ul').addClass('row');
		$('.product-grid ul li').addClass('span6');
		$('.product-grid ul li').each(function(index, element) {
			html = '';
					
			var image = $(element).find('.image').html();
			
			if (image != null) {
				html += '<div class="image">' + image + '</div>';
			}
			html += '<div class="left">';
			

			(function($){$.fn.equalHeights=function(minHeight,maxHeight){tallest=(minHeight)?minHeight:0;this.each(function(){if($(this).height()>tallest){tallest=$(this).height()}});if((maxHeight)&&tallest>maxHeight)tallest=maxHeight;return this.each(function(){$(this).height(tallest)})}})(jQuery)
				$(window).load(function(){
				if($(".subcatname.htm").length){
				$(".subcatname.htm").equalHeights()}
			});
			
			html += '<div class="name maxheight-subcat">' + $(element).find('.name').html() + '</div>';	
			
			html += '<div class="description">' + $(element).find('.description').html() + '</div>';
						
			html += '<div class="button details" style="float:right" >' + $(element).find('.details').html() + '</div>';
			
			html += '<div class="clear">' + $(element).find('.clear').html() + '</div>';
			var rating = $(element).find('.rating').html();
			
			if (rating != null) {
				html += '<div class="rating">' + rating + '</div>';
			}
			
			html += '</div>';
			$(element).html(html);
		});	
					
		$('.display').html('<b>Display:</b> <a id="list_a" onclick="display(\'list\');"><i class="icon-list"></i></a>  <div id="grid_b"><i class="icon-th"></i></i></div>');
		
		$.totalStorage('display', 'grid');
	}
	if ($('body').width() > 940) {
	// tooltip demo
		$('.tooltip-toggle').tooltip({
		selector: "a[data-toggle=tooltip]/index.htm"
		})
		$('.tooltip-1.htm').tooltip({
			placement:'bottom'
		})
		$('.tooltip-2.htm').tooltip({
			placement:'top'
		})
		}
	
}

view = $.totalStorage('display');

if (view) {
	display('grid');
} else {
	display('grid');
}
//--></script> 
<!--<script type="text/javascript">		(function($){$.fn.equalHeights=function(minHeight,maxHeight){tallest=(minHeight)?minHeight:0;this.each(function(){if($(this).height()>tallest){tallest=$(this).height()}});if((maxHeight)&&tallest>maxHeight)tallest=maxHeight;return this.each(function(){$(this).height(tallest)})}})(jQuery)
	$(window).load(function(){
		if($(".cat-height").length){
		$(".cat-height").equalHeights()}
	})
</script>-->

<div class="clear"></div>
</div>
</div>
</div>
<div class="clear"></div>
</section>

app/views/news/show.html.erb
<section>

<div id="container">

<div class="container">
<div id="notification"></div>
<div class="row">
<div class="span12">
<div class="row">
<div class="span12  " id="content">  <div class="breadcrumb">
		<a href="<%=plants_path%>">Home</a>
		 &raquo; <a href="<%=news_index_path%>">CẨM NANG THỦY SINH</a>
		 &raquo; <a href="<%=news_index_path%>"><%= @list_post_item.title %></a>
	  </div>
  <h1 class="style-1"><%= @list_post_item.title %></h1>
    
      
  <div class="product-grid">
	<ul>

<li class="span12 ">
	<div class="image"><a href=""><%=image_tag @list_post_item.image, id: 'img_40', style: 'width:430px; height:200px' %></a></div>
	<div class="description">
	<%="<span style= 'color:#002AE1'>Ngày đăng: </span>".html_safe + @list_post_item.created_at.strftime("%Y/%m/%d")%>

	<br/>
	<span style= "color:#002AE1">&nbsp;</span><%= @list_post_item.description.html_safe%>
	</div>
</li>

			 </ul>
  </div>
  
      </div>
	</div>
</div>

<script type="text/javascript"><!--
function display(view) {
	
		$('.product-list').attr('class', 'product-grid');
		$('.product-grid ul').addClass('row');
		$('.product-grid ul li').addClass('span12');
		$('.product-grid ul li').each(function(index, element) {
			html = '';
					
			var image = $(element).find('.image').html();
			
			if (image != null) {
				html += '<div class="image">' + image + '</div>';
			}
			html += '<div class="left">';
			

			(function($){$.fn.equalHeights=function(minHeight,maxHeight){tallest=(minHeight)?minHeight:0;this.each(function(){if($(this).height()>tallest){tallest=$(this).height()}});if((maxHeight)&&tallest>maxHeight)tallest=maxHeight;return this.each(function(){$(this).height(tallest)})}})(jQuery)
				$(window).load(function(){
				if($(".subcatname.htm").length){
				$(".subcatname.htm").equalHeights()}
			});		
		
			html += '<div class="description">' + $(element).find('.description').html() + '</div>';

			html += '<div class="clear">' + $(element).find('.clear').html() + '</div>';
			var rating = $(element).find('.rating').html();
			
					
			html += '</div>';
			$(element).html(html);
		});	
					
				
		$.totalStorage('display', 'grid');

	if ($('body').width() > 940) {
	// tooltip demo
		$('.tooltip-toggle').tooltip({
		selector: "a[data-toggle=tooltip]/index.htm"
		})
		$('.tooltip-1.htm').tooltip({
			placement:'bottom'
		})
		$('.tooltip-2.htm').tooltip({
			placement:'top'
		})
		}
	
}

view = $.totalStorage('display');

if (view) {
	display('grid');
} else {
	display('grid');
}
//--></script> 


<div class="clear"></div>
</div>
</div>
</div>
<div class="clear"></div>
</section>