config/routes.rb
Rails.application.routes.draw do
   get 'contacts/new'

  devise_for :accounts,  skip: :registrations
  get 'categories/index'

  root 'plants#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'chat' =>'chats#index'
  get 'login'    => 'sessionss#new'
  get 'registry' => 'accountss#new'
  post 'registry' => 'accountss#create'
   
  delete 'login' => 'sessionss#destroy'
  controller :sessionss do
      post 'login'   => :create
      get 'sessionss/destroy' => 'sessionss#destroy'
  end

  resources :accountss do
     member do
          post "edit" => 'accountss#update'
    end
  end
  controller :accountss do
        post 'accountss/new' => 'accountss#create'
  end
  resources :plants
  resources :categories
  resources :contacts 
  resources :shops
  resources :searchs
  resources :news
  resources :advs do
    get 'destroy'
    get 'destroy_message'
    member do
          post "edit" => 'advs#update'
    end
    collection do
          get 'advs/add_message'
    end
  end
  controller :advs do
        post 'advs/new' => 'advs#create'
  end
  controller :contacts do
        post 'contacts/new' => 'contacts#create'
    end
end

app/controllers/accountss_controller.rb
class AccountssController < ApplicationController
	layout 'public'

	before_action :check_session, :only =>[:index, :edit, :show]
	before_action :find_user_session, :only => [:index, :edit, :update]
	before_action :check_params_password, :only => [:update]
	before_action :find_user_by_id, :only   => [:show]

	def index
		if session[:role_account] == nil
			@advs = PostSell.where(:user_account_id  => session[:account_id]).order('created_at desc')
		else
			@advs = nil
		end
	end

	def new
		flash[:error] = ''
		@user_account = UserAccount.new
	end

	def create

		if params[:password_confirm]
			if params[:password_confirm] != params[:user_account][:password]
				flash[:error] = '&#8226; '.html_safe + 'Mật khẩu không đúng'
				# render 'new'
			end	
		else 
			flash[:error] = '&#8226; '.html_safe + 'Không được để trống'
			# render 'new'
		end	
		@user_account = UserAccount.new(use_params)
		if @user_account.save
			flash[:new_account] = params[:user_account][:usename]
			redirect_to login_path
		else
			respond_to do |format|
		        format.html { render :new }
		        format.json { render json: @user_account.errors, status: :unprocessable_entity }
        	end
		end
	end

	def edit
		flash[:error_password_old] = ''
		flash[:error_password_confirm] = ''
	end

	def update
		if params[:password] != ''
			if @user_account_login.update(use_params_update.merge(password: params[:password] ))
				redirect_to accountss_index_path
			else
				respond_to do |format|
			        format.html { render :edit }
			        format.json { render json: @user_account_login.errors, status: :unprocessable_entity }
	        	end
			end
		else
			if @user_account_login.update(use_params_update)
				redirect_to accountss_index_path
			else
				respond_to do |format|
			        format.html { render :edit }
			        format.json { render json: @user_account_login.errors, status: :unprocessable_entity }
	        	end
			end
		end
	end

	def show
		@advs = PostSell.where(:user_account_id  => @user_account_login.id).order('created_at desc')
	end

	private
		def use_params
	      params.require(:user_account).permit(:name, :image, :address, :phone_number, :birthday, :password, :usename, :image)
	    end

	    def use_params_update
	      params.require(:user_account_login).permit(:name, :image, :address, :phone_number, :birthday, :usename, :image)
	    end

	    def find_user_session
	    	if session[:role_account] == 'admin'
	    		@user_account_login = Account.find(session[:account_id])
	    	else
	    		@user_account_login = UserAccount.find(session[:account_id])
	    	end
	    end

	    def find_user_by_id
	    	@user_account_login = UserAccount.find(params[:id])
	    end

	    # check password and confirm password when user wanna update their password
	    def check_params_password
	    	binding.pry
	    	flash[:error_password_old] = ''
			flash[:error_password_confirm] = ''
			if params[:password_old] != '' && params[:password] != '' && params[:password_confirm] != ''
				if params[:password_old] != @user_account_login.password
					flash[:error_password_old] = 'Mật khẩu không đúng'
					render 'edit'
				else
					if params[:password] != params[:password_confirm]
						flash[:error_password_confirm] = 'Mật khẩu xác thực không đúng '
						render 'edit'
				
					end
				end
			end
	    end
end

app/helpers/accountss_helper.rb
module AccountssHelper
end

app/views/accountss/edit.html.erb
<div class="container">
  <div id="notification"></div>
  <div class="row">
    <div class="span12">
      <div class="row">
        <div class="span9  " id="content">  <div class="breadcrumb">
          <a href="">Home</a>
          &raquo; <a href="<%=accountss_path(@user_account_login)%>">THÔNG TIN CÁ NHÂN</a>
          &raquo; <a href="">THAY ĐỔI THÔNG TIN</a>
        </div>
        <div class="product-info">
<div class="row">
            
<div class="span9">
  <div class="tabs">
    <div class="tab-heading" id="s1">THÔNG TIN CÁ NHÂN</div>
    <div class="description" style="padding-bottom:0px">
      <div class="product-section">
          <%=form_for :user_account_login, :html => {:class => 'form-horizontal', :id => "register"} do |f|%>
    <h2>THAY ĐỔI THÔNG TIN CÁ NHÂN </h2>
    <hr/>
    <div class="content">
      <table class="form">
        <tbody><tr>
          <td>
            <div class="control-group">
              <label class="control-label" for="firstname"><span class="required">*</span> Họ tên:</label>
              <div class="controls">
                <%=f.text_field :name, class: 'q1 span3', :required => true%>
                <%= @user_account_login.errors[:name][0] === nil ?  '' : '&#8226;
'.html_safe + @user_account_login.errors[:name][0] %>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <div class="control-group">
              <label class="control-label" for="lastname"><span class="required"></span> Địa chỉ:</label>
              <div class="controls">
                <%=f.text_field :address, class: 'q1 span3' , :required => true%>
              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <div class="control-group">
              <label class="control-label" for="email"><span class="required"></span> Ngày sinh:</label>
              <div class="controls">
                <%=f.date_field :birthday, class: 'q1', placeholder: 'yyyy/mm/dd'%>

              </div>
            </div>
          </td>
        </tr>
        <tr>
          <td>
            <div class="control-group">
              <label class="control-label" for="telephone"><span class="required">*</span> Số điện thoại:</label>
              <div class="controls">
                <%=f.text_field :phone_number, class: 'q1'%>
                <%= @user_account_login.errors[:phone_number][0] === nil ?  '' : '&#8226;
'.html_safe + @user_account_login.errors[:phone_number][0] %>
              </div>
            </div>
          </td>
        </tr>
        <tr>
      <td>
        <div class="control-group">
          <label class="control-label" for="confirm"><span class="required"></span> Hình ảnh đại diện:</label>
          <div class="controls">
            <%=f.file_field :image, class: 'q1'%>
            <br/>
            <%if @user_account_login.image%>
            <%=image_tag @user_account_login.image , style: 'width: 200px; height:150px;'%>
            <%end%>
          </div>
        </div>
      </td>
    </tr>
      </tbody></table>
    </div>
<div class="content">

  <h2 id='s2'>THAY ĐỔI THÔNG TIN TÀI KHOẢN</h2>
  <hr/>
  <table class="form">
    <tbody>
    <tr>
      <td>
        <div class="control-group">
          <label class="control-label" for="password"><span class="required">*</span> Mật khẩu cũ:</label>
          <div class="controls">
            <%=password_field_tag :password_old,'', class: 'q1 ' %>
           <%=flash[:error_password_old]%>

          </div>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="control-group">
          <label class="control-label" for="password"><span class="required">*</span> Mật khẩu mới:</label>
          <div class="controls">
            <%=password_field_tag :password, '', class: 'q1'%>

          </div>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="control-group">
          <label class="control-label" for="confirm"><span class="required">*</span> Xác nhận Mật khẩu mới:</label>
          <div class="controls">
            <%=password_field_tag :password_confirm ,'', class: 'q1'%><%= flash[:error_password_confirm]%>
               
          </div>
        </div>
      </td>
    </tr>
    <%= @user_account_login.errors[:password][0] === nil ?  '' : '&#8226;
'.html_safe + @user_account_login.errors[:password][0] %>

  </tbody></table>

</div>
<div class="buttons">
  <div class="right">
      <a onclick="$('#register').submit();" class="button"><span>CẬP NHẬT</span></a>
    </div>
  </div>
<%end%>
           
      </div>
    </div>
  </div>
</div>
</div>
  
      </div>

    </div>


    <!-- Left menu -->
    <aside class="span3 aside" id="column-left">
      <div class="box account">
        <div class="box-heading">DANH MỤC</div>
        <div class="box-content">
          <ul class="acount list_product">
            <li><a href="#s1">THÔNG TIN CÁ NHÂN</a></li>
            <li><a href="#s2">THÔNG TIN TÀI KHOẢN</a></li>
          </ul>
        </div>
       </div>
      </aside>
    </div>
  </div>
    <div class="clear"></div>
</div>
</div>

app/views/accountss/index.html.erb
<div class="container">
  <div id="notification"></div>
  <div class="row">
    <div class="span12">
      <div class="row">
        <div class="span9  " id="content">  <div class="breadcrumb">
          <a href="<%=plants_path%>">Home</a>
          &raquo; <a href="<%=accountss_path(@user_account_login)%>">THÔNG TIN CÁ NHÂN</a>
        </div>
        <div class="product-info">
          <div class="row">
            
<div class="span9">
  <div class="tabs">
    <div class="tab-heading" id="s1">THÔNG TIN CÁ NHÂN</div>
    <div class="description" style="padding-bottom:0px">
      <div class="product-section">
        <div class="row">
          <div class="span5 fleft">
            <% if session[:role_account] %>
               <h3><span>HỌ TÊN: </span><%= @user_account_login.name%></h3>
              <p><span class="advs_style">Chức vụ:</span>
                <%if @user_account_login.role? :super_admin %>
                  Superadmin
                <%else%>
                  admin
                <%end%>
          

               </p>
              <p><span class="advs_style">Địa chỉ:</span> <%=@user_account_login.address%></p>
              <p><span class="advs_style">Ngày đăng kí:</span> <%=@user_account_login.created_at.strftime('%d - %m - %Y')%></p>
            <%else%>
            <h3><span>HỌ TÊN: </span><%=@user_account_login.name%></h3>
            <p><span class="advs_style">Ngày sinh:</span> <%=@user_account_login.birthday.strftime('%d - %m - %Y')%></p>
            <p><span class="advs_style">Số điện thoại:</span> <%=@user_account_login.phone_number%></p>
            <p><span class="advs_style">Tên tài khoản:</span> <%=@user_account_login.usename%></p>
            <p><span class="advs_style">Ngày đăng kí:</span> <%=@user_account_login.created_at.strftime('%d - %m - %Y')%></p>
            <%end%>
           
          </div>
         
            <%=image_tag@user_account_login.image, class: 'fright', style:'width:275px; height:183px'%>
            <br/>
            <p><span>Ảnh đại diện:</span></p>
          
          <div class="span9">
          <hr/>
           <% if session[:account_id] == @user_account_login.id and session[:role_account] == nil%>
            
            <%=link_to 'Cập nhật thông tin', edit_accountss_path(@user_account_login.id), class: 'btn'%>
            <%end%>
          </div>        
      </div>
      </div>
    </div>
  </div>
</div>
</div>
  <div class="tabs">
    <div class="tab-heading" id="s2" >CÁC HOẠT ĐỘNG GẦN ĐÂY</div>
    <div class="description"  style="padding-bottom:0px">
      <div class="product-section">
        <h3>CÁC BÀI ĐÃ ĐĂNG</h3>
        <hr>
        <%if @advs%>
        <%@advs.each do |a|%>
          <p>
            <%=a.created_at.strftime('%d/%m/%Y')%>
            <span>đã viết:</span> 
            <%=link_to a.title , adv_path(a.id), class: 'link_advs'%>
          </p>
        <%end%>
        <%end%>
      </div>

    </div>
  </div>
      </div>

    </div>


    <!-- Left menu -->
    <aside class="span3 aside" id="column-left">
      <div class="box account">
        <div class="box-heading">DANH MỤC</div>
        <div class="box-content">
          <ul class="acount list_product">
            <li><a href="#s1">THÔNG TIN CÁ NHÂN</a></li>
            <li><a href="#s2">CÁC HOẠT ĐỘNG GẦN ĐÂY</a></li>
          </ul>
        </div>
       </div>
      </aside>
    </div>
  </div>
    <div class="clear"></div>
</div>
</div>

app/views/accountss/new.html.erb
<div class="container">
<h1>Register Account</h1>
<center>
<div class="row">
<div class="span2"></div>
<div class="span8">
<div class="box-container">
	<%=form_for :user_account, :html => {:class => 'form-horizontal', :id => "register"} do |f|%>
		<h2>THÔNG TIN CÁ NHÂN</h2>
		<div class="content">
			<table class="form">
				<tbody><tr>
					<td>
						<div class="control-group">
							<label class="control-label" for="firstname"><span class="required">*</span> Họ tên:</label>
							<div class="controls">
								<%=f.text_field :name, class: 'q1 span3', :required => true%>
								<%= @user_account.errors[:name][0] === nil ?  '' : '&#8226;
'.html_safe + @user_account.errors[:name][0] %>
							</div>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div class="control-group">
							<label class="control-label" for="lastname"><span class="required"></span> Địa chỉ:</label>
							<div class="controls">
								<%=f.text_field :address, class: 'q1 span3' , :required => true%>
							</div>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div class="control-group">
							<label class="control-label" for="email"><span class="required"></span> Ngày sinh:</label>
							<div class="controls">
								<%=f.date_field :birthday, class: 'q1', placeholder: 'yyyy/mm/dd'%>

							</div>
						</div>
					</td>
				</tr>
				<tr>
					<td>
						<div class="control-group">
							<label class="control-label" for="telephone"><span class="required">*</span> Số điện thoại:</label>
							<div class="controls">
								<%=f.text_field :phone_number, class: 'q1'%>
								<%= @user_account.errors[:phone_number][0] === nil ?  '' : '&#8226;
'.html_safe + @user_account.errors[:phone_number][0] %>
							</div>
						</div>
					</td>
				</tr>
			</tbody></table>
		</div>
	
<h2>ĐĂNG KÍ TÀI KHOẢN</h2>
<div class="content">
	<table class="form">
		<tbody>
		<tr>
			<td>
				<div class="control-group">
					<label class="control-label" for="password"><span class="required">*</span> Tên tài khoản:</label>
					<div class="controls">
						<%=f.text_field :usename, class: 'q1 ', :required => true%>
						<%= @user_account.errors[:usename][0] === nil ?  '' : '&#8226;
'.html_safe + @user_account.errors[:usename][0] %>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="control-group">
					<label class="control-label" for="password"><span class="required">*</span> Mật khẩu:</label>
					<div class="controls">
						<%=f.password_field :password, class: 'q1 ', :required => true%>
						<%= @user_account.errors[:password][0] === nil ?  '' : '&#8226;
'.html_safe + @user_account.errors[:password][0] %>

					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="control-group">
					<label class="control-label" for="confirm"><span class="required">*</span> Xác nhận Mật khẩu:</label>
					<div class="controls">
						<%=password_field_tag :password_confirm, '', class: 'q1', :required => true%>
						<br/><%= flash[:error]%>
					</div>
				</div>
			</td>
		</tr>
		<tr>
			<td>
				<div class="control-group">
					<label class="control-label" for="confirm"><span class="required"></span> Hình ảnh đại diện:</label>
					<div class="controls">
						<%=f.file_field :image, class: 'q1'%>
					</div>
				</div>
			</td>
		</tr>
	</tbody></table>
</div>
<div class="buttons">
	<div class="right">
			<a onclick="$('#register').submit();" class="button"><span>Đăng kí</span></a>
		</div>
	</div>
<%end%>
</div>
</div>
</div>
</center>
</div>

app/views/accountss/show.html.erb
<div class="container">
  <div id="notification"></div>
  <div class="row">
    <div class="span12">
      <div class="row">
        <div class="span9  " id="content">  <div class="breadcrumb">
          <a href="">Home</a>
          &raquo; <a href="<%=accountss_path(@user_account_login)%>">THÔNG TIN CÁ NHÂN</a>
        </div>
        <div class="product-info">
          <div class="row">
            
<div class="span9">
  <div class="tabs">
    <div class="tab-heading" id="s1">THÔNG TIN CÁ NHÂN</div>
    <div class="description" style="padding-bottom:0px">
      <div class="product-section">
        <div class="row">
          <div class="span5 fleft">
            <h3><span>HỌ TÊN: </span><%=@user_account_login.name%></h3>
            <p><span class="advs_style">Ngày sinh:</span> <%=@user_account_login.birthday.strftime('%d - %m - %Y')%></p>
            <p><span class="advs_style">Số điện thoại:</span> <%=@user_account_login.phone_number%></p>
            <p><span class="advs_style">Tên tài khoản:</span> <%=@user_account_login.usename%></p>
            <p><span class="advs_style">Ngày đăng kí:</span> <%=@user_account_login.created_at.strftime('%d - %m - %Y')%></p>

           
          </div>
         
            <%=image_tag@user_account_login.image, class: 'fright', style:'width:275px; height:183px'%>
            <br/>
            <p><span>Ảnh đại diện:</span></p>     
      </div>
      </div>
    </div>
  </div>
</div>
</div>
  <div class="tabs">
    <div class="tab-heading" id="s2" >CÁC HOẠT ĐỘNG GẦN ĐÂY</div>
    <div class="description"  style="padding-bottom:0px">
      <div class="product-section">
        <h3>CÁC BÀI ĐÃ ĐĂNG</h3>
        <hr>
        <%@advs.each do |a|%>
          <p>
            <%=a.created_at.strftime('%d/%m/%Y')%>
            <span>đã viết:</span> 
            <%=link_to a.title , adv_path(a.id), class: 'link_advs'%>
          </p>
        <%end%>
      </div>

    </div>
  </div>
      </div>

    </div>


    <!-- Left menu -->
    <aside class="span3 aside" id="column-left">
      <div class="box account">
        <div class="box-heading">DANH MỤC</div>
        <div class="box-content">
          <ul class="acount list_product">
            <li><a href="#s1">THÔNG TIN CÁ NHÂN</a></li>
            <li><a href="#s2">CÁC HOẠT ĐỘNG GẦN ĐÂY</a></li>
          </ul>
        </div>
       </div>
      </aside>
    </div>
  </div>
    <div class="clear"></div>
</div>
</div>