config/routes.rb
Rails.application.routes.draw do
   get 'contacts/new'

  devise_for :accounts,  skip: :registrations
  get 'categories/index'

  root 'plants#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'chat' =>'chats#index'
  get 'login'    => 'sessionss#new'
  get 'registry' => 'accountss#new'
  post 'registry' => 'accountss#create'
   
  delete 'login' => 'sessionss#destroy'
  controller :sessionss do
      post 'login'   => :create
      get 'sessionss/destroy' => 'sessionss#destroy'
  end

  resources :accountss do
     member do
          post "edit" => 'accountss#update'
    end
  end
  controller :accountss do
        post 'accountss/new' => 'accountss#create'
  end
  resources :plants
  resources :categories
  resources :contacts 
  resources :shops
  resources :searchs
  resources :news
  resources :advs do
    get 'destroy'
    get 'destroy_message'
    member do
          post "edit" => 'advs#update'
    end
    collection do
          get 'advs/add_message'
    end
  end
  controller :advs do
        post 'advs/new' => 'advs#create'
  end
  controller :contacts do
        post 'contacts/new' => 'contacts#create'
    end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      # user ||= User.new # guest user (not logged in)
      # if user.role? :member
      #   can :manage, :all
      #   can :access, :rails_admin
      # else
      #    can :manage, [Plant]
      #    can :access, :rails_admin
      # end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities                 # allow everyone to read everything
    $session_account_admin = nil
    if user && user.admin?
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard                  # allow access to dashboard
      if user.role? :super_admin
        can [:read, :destroy], PostSell    
        can [:read, :destroy], UserAccount  
        can :manage, [Plant, PlantImage, Account, Category, Post, Shop, Technical, Contact, Role]            # allow superadmins to do anything
      elsif user.role? :member
         can [:read, :create, :update], [Plant, PlantImage, Post, Technical, Shop]
         can [:read, :destroy], Contact
         can [:show, :update], Account, :id => user.id
      elsif user.role? :guest
        # can :update, Product, :hidden => false  # allow sales to only update visible products
      end
      $session_account_admin = user.id
    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :validatable

   has_and_belongs_to_many  :roles 
   has_many :posts
   accepts_nested_attributes_for :roles
	def role?(role)
	    return !!self.roles.find_by_name(role.to_s)
	end

  before_save do
    self.image = self.file.original_file
  end

	mount_uploader :image, ImageUploader
end

app/models/accounts_role.rb
class AccountsRole < ActiveRecord::Base
	belongs_to :account
	belongs_to :role
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :plants
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, :email, :phone_number, :description,
     	:presence =>  { :message => "Không được để trống" }, :on => :create
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user_account
	belongs_to :post_sell
end

app/models/plant.rb
class Plant < ActiveRecord::Base
  belongs_to :category
  has_many :plant_images
  belongs_to :technical

  accepts_nested_attributes_for :plant_images

  validates :technical, :category, presence: true

end

app/models/plant_image.rb
class PlantImage < ActiveRecord::Base
  belongs_to :plant

  mount_uploader :image, ImageUploader

  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :account

  mount_uploader :image, ImageUploader
end

app/models/post_sell.rb
class PostSell < ActiveRecord::Base
	self.inheritance_column = :foo
	belongs_to :user_account
	has_many :messages

	mount_uploader :image, ImageUploader
end

app/models/role.rb
class Role < ActiveRecord::Base
 has_and_belongs_to_many :accounts
end

app/models/shop.rb
class Shop < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/models/technical.rb
class Technical < ActiveRecord::Base
  has_one :plant
end

app/models/user_account.rb
class UserAccount < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	has_many :post_sells 
  has_many :messages
  #validate cant be blank
  	validates :name, :usename, :password, :phone_number,
     	:presence =>  { :message => "Không được để trống" }, :on => :create

    #validate number text
  	validates :phone_number, 
  		numericality: { only_integer: true, :message=>"Chỉ được nhập số tự nhiên"},
  		length: { minimum: 10, too_short: " Tối thiểu 10 chữ số",
                maximum: 11, too_long: " Tối đa 11 chữ số" }
  		# length: { maximum: 11, too_long: " Tối đa 11 chữ số" }

  	#validate lenght
  	validates :name, :usename, :password, :address, 
  		length: { minimum: 8, too_short: " Độ dài tối thiểu 8 ký tự" },
  		length: { maximum: 255, too_long: "Chỉ nhập tối đa 255 ký tự" }

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  layout  'application',  :only  => [:index]
  layout  'public', :only => [:show]
  before_action :find_plant_id, :only => [:show]

  def index
    @list_item_news = type_news.all.limit(6).order('created_at desc')
    
    if $session_account_admin
       session[:account_id] = $session_account_admin
       session[:role_account] = 'admin'
       # binding.pry
    end
    $session_account_admin = nil
    # binding.pry
  end

  def show
  	@plantimage = PlantImage.where(:plant_id => @plant_id).limit(4)
  	                        .order(:created_at =>  'desc')
  	@count_i    = @plantimage.size
  	@plant_relasted = Plant.where(:category_id => @plant_id.category_id)
  					  .where.not(:id=> @plant_id)
  					  .limit(8).order("RAND()")
    @plant_id.technical_id ? @technical = Technical.find(@plant_id.technical_id) : ''
   end

  def edit
  end



  private
    def find_plant_id
  		@plant_id = Plant.find(params[:id])
  	end

    def type_news
      params[:type] ? @type_news = params[:type] : @type_news = 'plant'
      @type_news.camelize.constantize
    end  
end

app/helpers/accountss_helper.rb
module AccountssHelper
end

app/helpers/advs_helper.rb
module AdvsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/plants/index.html.erb
      <div class="box featured">
        <div class="box-heading">DANH SÁCH TIN TỨC</div>
        <div class="box-content">
          <div class="box-product">

            <ul class="row">
            <% if params[:type] == 'plant' or params[:type] == nil %>
              <%@list_item_news.each do |lin| %>
              <li class="span3">
                  <div class="image2">
                    <a href="<%=plant_path(lin.id)%>"><img id="img_34" src="<%=lin.plant_images[0].image%>" alt="Fusce et mauris sit" class="image_view"/></a>
                    <a href="<%=plant_path(lin.id)%>" rel="colorbox" class="colorbox1 quick-view-button"><i class=" icon-search "></i></a>
                  </div>
                  <div class="inner">
                    <div class="f-left">
                      <div class="name maxheight-feat"><a href="<%plant_path(lin.id)%>"><%=lin.name%></a></div>
                      <div class="description"><%= truncate lin.address, length: 100%></div>
                    </div>
                    <div class="cart-button">
                      <div class="cart"><a title="Xem tiếp" href="<%=plant_path(lin.id)%>" class="button addToCart"> <span>Xem tiếp</span></a></div>
                      <span class="clear"></span>
                    </div>
                    <div class="clear"></div>
                  </div>
                  <div class="clear"></div>
              </li>
              <%end%>
            <%elsif params[:type] == 'shop'%>
              <%@list_item_news.each do |lin| %>
              <li class="span3">
                  <div class="image2">
                    <a href="<%=shops_path%>"><img id="img_34" src="<%=lin.image%>" alt="Fusce et mauris sit" class="image_view"/></a>
                    <a href="<%=shops_path%>" rel="colorbox" class="colorbox1 quick-view-button"><i class=" icon-search "></i></a>
                  </div>
                  <div class="inner">
                    <div class="f-left">
                      <div class="name maxheight-feat"><a href="<%=shops_path%>"><%=lin.name%></a></div>
                      <div class="description">
                        <span style="color:#002AE1"></span><%= lin.address%></div>
                    </div>
                    <div class="cart-button">
                      <div class="cart"><a title="Xem tiếp" href="<%=shops_path%>" class="button addToCart"> <span>Xem tiếp</span></a></div>
                      <span class="clear"></span>
                    </div>
                    <div class="clear"></div>
                  </div>
                  <div class="clear"></div>
              </li>
              <%end%>
            <%elsif params[:type] == 'post'%>
                <%@list_item_news[0..1].each do |lin| %>
              <li class="span9">
                  <div class="image2">
                    <a href="<%=shops_path%>"><img id="img_34" src="<%=lin.image%>" alt="Fusce et mauris sit" class="image_post_index fleft"/></a>
                    <div class=" fleft span5 image3">
                       <h3><%=lin.title%></h3>
                       <p><%= lin.detail%></p>
                       <div class="cart-button">
                      <div class="cart"><a title="Xem tiếp" href="<%=news_path(lin.id)%>" class="button addToCart"> <span>Xem tiếp</span></a></div>
                      <span class="clear"></span>
                    </div>
                    </div>
                  </div>
                  <div class="inner bottom-border">
                 </div>
              </li>
              <%end%>

            <%else params[:type] == 'post_sell'%>
              <%@list_item_news.each do |lin| %>
              <li class="span3">
                  <div class="image2">
                    <% if lin.image.url != nil %>
                      <a href="<%=adv_path(lin.id)%>"><img id="img_34" src="<%=lin.image%>" alt="Fusce et mauris sit" class="image_view"/></a>
                      <a href="<%=adv_path(lin.id)%>" rel="colorbox" class="colorbox1 quick-view-button"><i class=" icon-search "></i></a>
                    <%else%>
                      <a href="<%=adv_path(lin.id)%>"><img id="img_34" src="/no_image.jpg" alt="Fusce et mauris sit" class="image_view"/></a>
                      <a href="<%=adv_path(lin.id)%>" rel="colorbox" class="colorbox1 quick-view-button"><i class=" icon-search "></i></a>
                    <%end%>
                  </div>
                  <div class="inner">
                    <div class="f-left">
                      <div class="name maxheight-feat"><a href="<%=adv_path(lin.id)%>"><%=lin.title%></a></div>
                      <div class="description">
                        <span style="color:#002AE1">Hình thức:</span><%= lin.type%></div>
                    </div>
                    <div class="cart-button">
                      <div class="cart"><a title="Xem tiếp" href="<%=adv_path(lin.id)%>" class="button addToCart"> <span>Xem tiếp</span></a></div>
                      <span class="clear"></span>
                    </div>
                    <div class="clear"></div>
                  </div>
                  <div class="clear"></div>
              </li>
              <%end%>
            <%end%>
            </ul>
          </div>
          <div class="clear"></div>
        </div>
      </div>

app/views/plants/show.html.erb
<div class="container">
  <div id="notification"></div>
  <div class="row">
    <div class="span12">
      <div class="row">
        <div class="span9  " id="content">  <div class="breadcrumb">
          <a href="<%=plants_path%>">Home</a>
          &raquo; <a href="<%=category_path(@plant_id.category.id)%>"><%=@plant_id.category.name%></a>
          &raquo; <a href=""><%=@plant_id.name%></a>
        </div>
        <div class="product-info">
          <div class="row">
            <div class="span3">
              <h1 class="view">Hình Ảnh</h1>
              <script type="text/javascript">
              jQuery(document).ready(function(){
              var myPhotoSwipe = $("#gallery a").photoSwipe({ enableMouseWheel: false , enableKeyboard: false, captionAndToolbarAutoHideDelay:0 });
              });
              </script>
              <div id="full_gallery">
                <ul id="gallery">
                  <% @plantimage[0..(@count_i)].each do |pi|%>
                  <li><a href="<%=pi.image %>" data-something="something" data-another-thing="anotherthing"> <%=image_tag pi.image%></a></li>
                  <%end%>
                </ul>
              </div>
              <div id="default_gallery" class="left spacing">
                  <% @plantimage[0..(@count_i)].each do |pi|%>
                    <div class="zoom-top">
                      <a href="<%=pi.image%>" title="Hình Ảnh"  data-gal="prettyPhoto[gallery1]" >
                         <%=image_tag pi.image%>
                     </a>
                    </div>
                  <%end%>
                <div class="image">
                  <a href="<%=@plantimage[0].image%>" title="Hình Ảnh" class = 'cloud-zoom' id='zoom1' rel="position: 'right'" >
                    <%=image_tag @plantimage[0].image%>
                  </a>
                  <a href="<%=@plantimage[0].image%>" title="Hình Ảnh">
                  </a>
                </div>
                <div class="image-additional">
                  <ul id="image-additional">
                    <% @plantimage[1..(@count_i)].each do |pi|%>
                    <li>
                      <a href="<%=pi.image %>" title="Hình Ảnh" class="cloud-zoom-gallery" rel="useZoom: 'zoom1', smallImage: '' "><%=image_tag pi.image, style: 'width:75px; height:50px' %></a>
                    </li>
                    <%end%>
                  </ul>
                  <div class="clear"></div>
                </div>
              </div>
            </div>
<div class="span6">
  <div class="tabs">
    <div class="tab-heading" id="s1">GIỚI THIỆU</div>
    <div class="description" style="padding-bottom:0px">
      <div class="product-section">
        <table width="100%">
          <tr>
            <th style="width:30%"></th>
            <th style="width:70%"></th>
          </tr>
          <tr>
            <td class="title_plant_item"> Tên thường gọi:</td>
            <td class="name_plant_item " style="text-transform: uppercase;"><%=@plant_id.name%></td>
          </tr>
          <tr>
            <td class="title_plant_item"> Tên Khoa học:</td>
            <td class="name_plant_item_low" style="text-transform: uppercase;"><%=@plant_id.scientic_name%></td>
          </tr>
          <tr>
            <td class="title_plant_item"> Thuộc Chi:</td>
            <td class="name_plant_item_low" ><%=@plant_id.genus%></td>
          </tr>
          <tr>
            <td class="title_plant_item"> Thuộc Họ:</td>
            <td class="name_plant_item_low"><%=@plant_id.familia%></td>
          </tr>
          <tr>
            <td class="title_plant_item"> Phân loại:</td>
            <td class="name_plant_item_low"><%=@plant_id.category.name%></td>
          </tr>
          <tr>
            <td class="title_plant_item"> Xuất xứ:</td>
            <td class="name_plant_item_low"><%=@plant_id.address%></td>
          </tr>
          <tr>
            <td class="title_plant_item"> Ngày đăng:</td>
            <td class="name_plant_item_low"><%=@plant_id.created_at.strftime('%d - %m -%Y')%></td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>
</div>
  <div class="tabs">
    <div class="tab-heading" id="s2" >ĐẶC TÍNH SINH HỌC</div>
    <div class="description"  style="padding-bottom:0px">
      <div class="product-section">
        <% if @technical %>
        <table width="100%" class="table table-hover">
          <tr>
            <td width="20%" class="title_plant_item"> Độ khó:</td>
            <td width="80%" class="name_plant_item_low">
               <%=@technical.level%>
            </td>
          </tr>
          <tr>
            <td class="title_plant_item">Độ pH:</td>
            <td class="name_plant_item_low" style="text-transform: uppercase;">
              <%=@technical.pH%>
            </td>
          </tr>
          <tr>
            <td class="title_plant_item">Nhiệt độ:</td>
            <td class="name_plant_item_low" style="text-transform: uppercase;">
              <%=@technical.temperature%>
            </td>
          </tr>
          <tr>
            <td class="title_plant_item">Phân nền :</td>
            <td class="name_plant_item_low" >
              <%=@technical.fertilizer%>
            </td>
          </tr>
          <tr>
            <td class="title_plant_item">Kích thước:</td>
            <td class="name_plant_item_low">
              <%=@technical.size%>
            </td>
          </tr>
          <tr>
            <td class="title_plant_item">Cấu trúc cây:</td>
            <td class="name_plant_item_low">
              <%=@technical.tree_structure%>
            </td>
          </tr>
          <tr>
            <td class="title_plant_item">Chế độ ánh sáng:</td>
            <td class="name_plant_item_low">
              <%=@technical.light%>
            </td>
          </tr>
          <tr>
            <td class="title_plant_item">Chế độ dinh dưỡng:</td>
            <td class="name_plant_item_low">
              <%=@technical.trophic%>
            </td>
          </tr>
          <tr>
            <td class="title_plant_item">Tốc độ sinh trưởng:</td>
            <td class="name_plant_item_low">
              <%=@technical.growth%>
           </td>
           <tr>
            <td class="title_plant_item">Ghi chú:</td>
            <td class="name_plant_item_low">
              <%=@technical.notice%>
           </td>
          </tr>
        </table>
        <%elsif%>
        <p> Dữ liệu chưa cập nhật</p>
        <%end%>
      </div>
    </div>
  </div>
        <div class="tabs">
          <div class="tab-heading" id="s3">THÔNG TIN CHI TIẾT</div>
          <div class="tab-content">
            <%=@plant_id.description.html_safe%>
          </div>
        </div>
      </div>
      <h1 class="style-1 mt0" id="s4">CÁC LOẠI CÂY LIÊN QUAN</h1>
      <div  class="related">
        <div class="box-product">
          <ul class="related-slider">
          <% @plant_relasted.each do |pr| %>
            <li class="related-info">
              <div class="image">
                <a href="<%= plant_path(pr.id)%>"><%= image_tag pr.plant_images[0].image, style: 'width:129px; height:90px;'%></a>
              </div>
              <div class="inner_related" style="padding-bottom: 5px;">
                <script type="text/javascript">
                if ($('.container.htm').width() > 723) {
                (function($){$.fn.equalHeights=function(minHeight,maxHeight){tallest=(minHeight)?minHeight:0;this.each(function(){if($(this).height()>tallest){tallest=$(this).height()}});if((maxHeight)&&tallest>maxHeight)tallest=maxHeight;return this.each(function(){$(this).height(tallest)})}})(jQuery)
                $(window).load(function(){
                if($(".maxheight-relat.htm").length){
                $(".maxheight-relat.htm").equalHeights()}
                });
                };
                </script>
                <div class="name maxheight-relat" style="text-align: center; margin-bottom:-6px;"><a href="<%= plant_path(pr.id)%>"><%=truncate pr.name ,length: 18%></a></div>
                <div class="cart-button">
                  <div class="cart" style="text-align: center;" >
                    <a title="Xem cây <%= pr.name%>" href="<%= plant_path(pr.id)%>" class="button ">
                      <span>Xem</span>
                    </a>
                  </div>
                  <span class="clear"></span>
                </div>
                <div class="rating">
                </div>
              </div>
            </li>
            <%end%>

          </ul>
        </div>
      </div>
    </div>


    <!-- Left menu -->
    <aside class="span3 aside" id="column-left">
      <div class="box account">
        <div class="box-heading">DANH MỤC THÔNG TIN</div>
        <div class="box-content">
          <ul class="acount list_product">
            <li><a href="#s1">GIỚI THIỆU</a></li>
            <li><a href="#s2">ĐẶC TÍNH SINH HỌC</a></li>
            <li><a href="#s3">THÔNG TIN CHI TIẾT </a></li>  
            <li><a href="#s4">CÁC LOẠI CÂY LIÊN QUAN</a></li>
          </ul>
        </div>
       </div>
        <script type="text/javascript">
        if ($('.container.htm').width() > 723) {
        (function($){$.fn.equalHeights=function(minHeight,maxHeight){tallest=(minHeight)?minHeight:0;this.each(function(){if($(this).height()>tallest){tallest=$(this).height()}});if((maxHeight)&&tallest>maxHeight)tallest=maxHeight;return this.each(function(){$(this).height(tallest)})}})(jQuery)
        $(window).load(function(){
        if($(".maxheight-spec.htm").length){
        $(".maxheight-spec.htm").equalHeights()}
        });
        };
        </script>
      </aside>
    </div>
  </div>
    <div class="clear"></div>
</div>
</div>